version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: sportz_postgres
    environment:
      POSTGRES_USER: sportz
      POSTGRES_PASSWORD: sportz123
      POSTGRES_DB: sportz
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sportz -d sportz"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
